apiVersion: v1
kind: Template
metadata:
  name: ds3-mysql-pvc
  annotations:
    description: "PVC for DS3 MySQL instance on OpenShift 3"
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${APP_NAME}-database-storage
  spec:
    storageClassName: ${STORAGE_CLASS}
    accessModes:
      - "ReadWriteOnce"
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
parameters:
- description: The name assigned to all of the frontend objects defined in this template.
  displayName: Name
  name: APP_NAME
  required: true
  value: ds3-mysql-master
- description: The size of the volume for MySQL data files.
  displayName: MySQL Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 10Gi
- description: The StorageClass to use to request the volume
  displayName: StorageClass for Source Volume
  name: STORAGE_CLASS
  required: true
  value: glusterfs-storage
